import { Metadata } from 'next'
import { Shield, FileText, CreditCard, Scale } from 'lucide-react'
import { Button } from '@/components/ui/button'
import Link from 'next/link'
export const metadata: Metadata = { title: 'Terms of Service — SkulHub', description: 'Terms and conditions for using SkulHub.' }
export default function TermsPage() {
  function S({icon:I,t,c}:{icon:any;t:string;c:React.ReactNode}) { return <section className="rounded-xl border bg-card p-6"><h2 className="mb-3 flex items-center gap-2 text-xl font-bold"><I className="h-5 w-5 text-emerald-600" />{t}</h2><div className="space-y-2 text-sm text-muted-foreground">{c}</div></section> }
  return (<div className="min-h-screen overflow-x-hidden bg-gradient-to-b from-emerald-50 via-white to-teal-50 dark:from-slate-950 dark:via-slate-900 dark:to-emerald-950"><header className="sticky top-0 z-50 border-b bg-background/80 backdrop-blur-md"><div className="mx-auto flex h-16 max-w-4xl items-center justify-between px-4"><Link href="/" className="flex items-center gap-2"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-gradient-to-br from-emerald-500 to-teal-600 text-white"><Shield className="h-5 w-5" /></div><span className="text-lg font-bold">SkulHub</span></Link><Button variant="outline" size="sm" asChild><Link href="/">Back to Home</Link></Button></div></header><main className="mx-auto max-w-3xl px-4 py-12"><div className="mb-8 text-center"><h1 className="text-3xl font-bold tracking-tight">Terms of Service</h1><p className="mt-2 text-sm text-muted-foreground">Last updated: {new Date().toLocaleDateString('en-KE')}</p></div><div className="space-y-6"><S icon={FileText} title="1. Acceptance" c={<p>By registering, you agree to these Terms. SkulHub is a school management platform for Kenyan schools.</p>} /><S icon={CreditCard} title="2. Subscription" c={<p>Three plans: Starter (KES 2,500/mo), Standard (KES 5,000/mo), Premium (KES 10,000/mo). 30-day free trial. Billed monthly via M-Pesa. Cancel anytime.</p>} /><S icon={Shield} title="3. Acceptable Use" c={<p>No malware, no unauthorized data access, no spam SMS, no reverse engineering, no credential sharing.</p>} /><S icon={Scale} title="4. Liability" c={<p>SkulHub is provided "as is". Maximum liability: 3 months of subscription fees.</p>} /><S icon={Scale} title="5. Governing Law" c={<p>Laws of the Republic of Kenya. Kenya Data Protection Act 2019 applies.</p>} /></div><div className="mt-12 flex justify-center gap-4"><Button asChild><Link href="/privacy">Privacy Policy</Link></Button><Button variant="outline" asChild><Link href="/">Home</Link></Button></div></main></div>)
}

