import { Metadata } from 'next'
import { Shield, Lock, Database, Eye, Users, Mail } from 'lucide-react'
import { Button } from '@/components/ui/button'
import Link from 'next/link'
export const metadata: Metadata = { title: 'Privacy Policy — SkulHub', description: 'How SkulHub collects, uses, and protects your personal data.' }
export default function PrivacyPolicyPage() {
  const S = ({icon:I,t,c}:{icon:any;t:string;c:React.ReactNode}) => <section className="rounded-xl border bg-card p-6"><h2 className="mb-3 flex items-center gap-2 text-xl font-bold"><I className="h-5 w-5 text-emerald-600" />{t}</h2><div className="space-y-2 text-sm text-muted-foreground">{c}</div></section>
  return (<div className="min-h-screen overflow-x-hidden bg-gradient-to-b from-emerald-50 via-white to-teal-50 dark:from-slate-950 dark:via-slate-900 dark:to-emerald-950"><header className="sticky top-0 z-50 border-b bg-background/80 backdrop-blur-md"><div className="mx-auto flex h-16 max-w-4xl items-center justify-between px-4"><Link href="/" className="flex items-center gap-2"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-gradient-to-br from-emerald-500 to-teal-600 text-white"><Shield className="h-5 w-5" /></div><span className="text-lg font-bold">SkulHub</span></Link><Button variant="outline" size="sm" asChild><Link href="/">Back to Home</Link></Button></div></header><main className="mx-auto max-w-3xl px-4 py-12"><div className="mb-8 text-center"><div className="mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-full bg-emerald-100 dark:bg-emerald-950/40"><Lock className="h-8 w-8 text-emerald-600" /></div><h1 className="text-3xl font-bold tracking-tight">Privacy Policy</h1><p className="mt-2 text-sm text-muted-foreground">Last updated: {new Date().toLocaleDateString('en-KE')}</p></div><div className="space-y-6"><S icon={Database} title="1. Data We Collect" c={<><p>We collect student data (name, admission number, grades, attendance, guardian contacts), staff data (name, email, role), and financial data (M-Pesa transactions, invoices).</p></>} /><S icon={Eye} title="2. How We Use Your Data" c={<><p>Data is used for school management: academic records, fee processing, SMS notifications, report cards, and parent portal access. We never sell data or use it for advertising.</p></>} /><S icon={Lock} title="3. Data Security" c={<><p>Passwords are bcrypt-hashed. HTTPS/TLS 1.3 for transit. Role-based access control. Parent authentication with rate limiting. Audit logging. Hosted on Vercel (SOC 2 Type II).</p></>} /><S icon={Users} title="4. Smart Features" c={<><p>Smart report comments and performance analytics use anonymized data. All generated content is reviewed by a human before publishing.</p></>} /><S icon={Database} title="5. Data Retention" c={<><p>Active student data retained while enrolled. Alumni records 7 years (KNEC). Financial records 7 years (KRA). Biometric templates deleted when student leaves.</p></>} /><S icon={Mail} title="6. Your Rights" c={<><p>Under Kenya Data Protection Act 2019: access, correct, delete, object, withdraw consent. Contact: <a href="mailto:privacy@skulhub.co.ke" className="text-emerald-600 hover:underline">privacy@skulhub.co.ke</a></p></>} /></div><div className="mt-12 flex justify-center gap-4"><Button asChild><Link href="/terms">View Terms</Link></Button><Button variant="outline" asChild><Link href="/">Home</Link></Button></div></main></div>)
}

